export interface SeedLesson {
  titleEn: string;
  titleEs: string;
  contentEn: string;
  contentEs: string;
  order: number;
}
export interface SeedQuestion {
  type: "MCQ" | "SCENARIO";
  questionEn: string;
  questionEs: string;
  scenarioEn?: string;
  scenarioEs?: string;
  options: { id: string; textEn: string; textEs: string }[];
  correctOptionId: string;
  explanationEn: string;
  explanationEs: string;
  order: number;
}
export interface SeedModule {
  order: number;
  titleEn: string;
  titleEs: string;
  subtitleEn: string;
  subtitleEs: string;
  isBonus: boolean;
  lessons: SeedLesson[];
  quizTitleEn: string;
  quizTitleEs: string;
  questions: SeedQuestion[];
}

function q(order: number, type: "MCQ" | "SCENARIO", qEn: string, qEs: string, opts: [string,string,string,string,string,string,string,string], correct: string, exEn: string, exEs: string, scEn?: string, scEs?: string): SeedQuestion {
  return {
    type, order, questionEn: qEn, questionEs: qEs, correctOptionId: correct,
    explanationEn: exEn, explanationEs: exEs,
    ...(scEn ? { scenarioEn: scEn, scenarioEs: scEs } : {}),
    options: [
      { id: "a", textEn: opts[0], textEs: opts[1] },
      { id: "b", textEn: opts[2], textEs: opts[3] },
      { id: "c", textEn: opts[4], textEs: opts[5] },
      { id: "d", textEn: opts[6], textEs: opts[7] },
    ],
  };
}

function lesson(order: number, tEn: string, tEs: string, cEn: string, cEs: string): SeedLesson {
  return { order, titleEn: tEn, titleEs: tEs, contentEn: cEn, contentEs: cEs };
}

export const modulesData1: SeedModule[] = [
  // ────────────── MODULE 1 ──────────────
  {
    order: 1, isBonus: false,
    titleEn: "Lash Fundamentals",
    titleEs: "Fundamentos de Pestañas",
    subtitleEn: "The building blocks of lash artistry",
    subtitleEs: "Los pilares del arte de las pestañas",
    quizTitleEn: "Lash Fundamentals Quiz",
    quizTitleEs: "Examen de Fundamentos de Pestañas",
    lessons: [
      lesson(1, "Natural Lash Anatomy", "Anatomía de la Pestaña Natural",
        "<p><strong>Understanding the natural lash</strong> is the foundation of every lash artist's career. Each natural eyelash consists of three parts: the <strong>bulb</strong> (root beneath the skin), the <strong>shaft</strong> (the visible lash), and the <strong>tip</strong>.</p><p>The upper eyelid has approximately <strong>90–150 lashes</strong> arranged in 5–6 rows, while the lower lid has about 70–80 lashes in 3–4 rows. Natural lashes grow to an average length of 8–12 mm on the upper lid.</p><p>Each lash sits in a <strong>hair follicle</strong> connected to a sebaceous gland that produces oils. Understanding this anatomy helps you isolate lashes properly and place extensions safely without damaging the follicle.</p>",
        "<p><strong>Comprender la pestaña natural</strong> es la base de la carrera de todo artista de pestañas. Cada pestaña natural consta de tres partes: el <strong>bulbo</strong> (raíz debajo de la piel), el <strong>tallo</strong> (la pestaña visible) y la <strong>punta</strong>.</p><p>El párpado superior tiene aproximadamente <strong>90–150 pestañas</strong> dispuestas en 5–6 filas, mientras que el inferior tiene unas 70–80 pestañas en 3–4 filas. Las pestañas naturales crecen a una longitud promedio de 8–12 mm en el párpado superior.</p><p>Cada pestaña se encuentra en un <strong>folículo piloso</strong> conectado a una glándula sebácea que produce aceites. Comprender esta anatomía te ayuda a aislar las pestañas correctamente y colocar las extensiones de forma segura sin dañar el folículo.</p>"),
      lesson(2, "Lash Growth Cycles", "Ciclos de Crecimiento de Pestañas",
        "<p>Natural lashes follow a three-phase growth cycle that directly impacts extension retention and application timing.</p><p><strong>Anagen (Active Growth Phase):</strong> Lasts 30–45 days. The lash is actively growing from the follicle. These lashes are thinner and shorter — be cautious about applying heavy extensions to baby lashes in this phase.</p><p><strong>Catagen (Transition Phase):</strong> Lasts 2–3 weeks. Growth stops and the follicle shrinks. This is an ideal phase for extension application as the lash is at or near full length.</p><p><strong>Telogen (Resting/Shedding Phase):</strong> Lasts 3–4 months. The lash remains in the follicle but is no longer growing and will eventually shed naturally. At any given time, most lashes are in this phase. Natural lash shedding of 1–5 lashes per day per eye is completely normal.</p>",
        "<p>Las pestañas naturales siguen un ciclo de crecimiento de tres fases que impacta directamente la retención de extensiones y el momento de aplicación.</p><p><strong>Anágena (Fase de Crecimiento Activo):</strong> Dura 30–45 días. La pestaña está creciendo activamente desde el folículo. Estas pestañas son más delgadas y cortas — ten cuidado al aplicar extensiones pesadas a pestañas bebé en esta fase.</p><p><strong>Catágena (Fase de Transición):</strong> Dura 2–3 semanas. El crecimiento se detiene y el folículo se encoge. Esta es una fase ideal para la aplicación de extensiones ya que la pestaña está en o cerca de su longitud completa.</p><p><strong>Telógena (Fase de Reposo/Caída):</strong> Dura 3–4 meses. La pestaña permanece en el folículo pero ya no crece y eventualmente caerá de forma natural. En cualquier momento dado, la mayoría de las pestañas están en esta fase. La caída natural de 1–5 pestañas por día por ojo es completamente normal.</p>"),
      lesson(3, "Types of Lash Extensions", "Tipos de Extensiones de Pestañas",
        "<p>Lash extensions vary across four key dimensions: <strong>curl type, diameter, length, and material</strong>.</p><p><strong>Curl Types:</strong> J curl (subtle, natural), B curl (slight lift), C curl (most popular, balanced curl), D curl (dramatic curl), L/L+ curl (flat base with sharp lift, great for hooded eyes).</p><p><strong>Diameter:</strong> Ranges from 0.03mm (mega volume) to 0.25mm (dramatic classic). Common classic diameters: 0.15mm, 0.18mm, 0.20mm. Volume diameters: 0.03mm–0.07mm.</p><p><strong>Materials:</strong> PBT (polybutylene terephthalate) is the industry standard — marketed as \"mink,\" \"silk,\" or \"synthetic.\" Real mink fur is rarely used due to ethical and allergy concerns. The terminology refers to finish: mink = matte, silk = semi-gloss, synthetic = glossy.</p>",
        "<p>Las extensiones de pestañas varían en cuatro dimensiones clave: <strong>tipo de curvatura, diámetro, longitud y material</strong>.</p><p><strong>Tipos de Curvatura:</strong> J (sutil, natural), B (ligero levantamiento), C (más popular, curvatura equilibrada), D (curvatura dramática), L/L+ (base plana con levantamiento pronunciado, ideal para ojos encapotados).</p><p><strong>Diámetro:</strong> Varía de 0.03mm (mega volumen) a 0.25mm (clásico dramático). Diámetros clásicos comunes: 0.15mm, 0.18mm, 0.20mm. Diámetros de volumen: 0.03mm–0.07mm.</p><p><strong>Materiales:</strong> PBT (tereftalato de polibutileno) es el estándar de la industria — comercializado como \"mink,\" \"seda,\" o \"sintético.\" La piel de visón real rara vez se usa por razones éticas y de alergia. La terminología se refiere al acabado: mink = mate, seda = semi-brillo, sintético = brillante.</p>"),
      lesson(4, "Natural Lash Health & Damage Prevention", "Salud de la Pestaña Natural y Prevención de Daños",
        "<p>A responsible lash artist always prioritizes the health of natural lashes. <strong>Damage occurs</strong> when extensions are too heavy, too long, or improperly applied.</p><p><strong>The golden rule:</strong> An extension should never be more than <strong>3mm longer or 1mm thicker</strong> than the natural lash. Overloading causes traction alopecia — permanent follicle damage from excessive weight.</p><p>Signs of lash damage include: gaps in the lash line, shorter-than-normal natural lashes, breakage at the midpoint, and client complaints of discomfort. If you see these signs, recommend a <strong>lash break</strong> and use a lash serum to promote recovery.</p>",
        "<p>Un artista de pestañas responsable siempre prioriza la salud de las pestañas naturales. <strong>El daño ocurre</strong> cuando las extensiones son demasiado pesadas, demasiado largas o se aplican incorrectamente.</p><p><strong>La regla de oro:</strong> Una extensión nunca debe ser más de <strong>3mm más larga o 1mm más gruesa</strong> que la pestaña natural. La sobrecarga causa alopecia por tracción — daño permanente al folículo por peso excesivo.</p><p>Los signos de daño en las pestañas incluyen: espacios en la línea de pestañas, pestañas naturales más cortas de lo normal, rotura en el punto medio y quejas de incomodidad del cliente. Si ves estos signos, recomienda un <strong>descanso de pestañas</strong> y usa un suero para promover la recuperación.</p>"),
      lesson(5, "Eye Shapes & Basic Lash Mapping", "Formas de Ojos y Mapeo Básico de Pestañas",
        "<p>Understanding <strong>eye shapes</strong> is critical for creating flattering lash designs. The seven main eye shapes are: almond, round, hooded, monolid, downturned, upturned, and close-set/wide-set.</p><p><strong>Basic lash mapping</strong> divides the eye into sections (inner corner, inner-mid, center, outer-mid, outer corner) and assigns specific lengths and curls to each zone. For example, a natural look uses shorter lengths at inner and outer corners with the longest at center.</p><p>Always assess the client's eye shape, natural lash condition, and desired look before creating a map. Document the map for consistency during fills.</p>",
        "<p>Comprender las <strong>formas de ojos</strong> es fundamental para crear diseños de pestañas favorecedores. Las siete formas principales de ojos son: almendrado, redondo, encapotado, monopárpado, caído, levantado y juntos/separados.</p><p><strong>El mapeo básico de pestañas</strong> divide el ojo en secciones (esquina interna, interna-media, centro, externa-media, esquina externa) y asigna longitudes y curvaturas específicas a cada zona. Por ejemplo, un look natural usa longitudes más cortas en las esquinas internas y externas con la más larga en el centro.</p><p>Siempre evalúa la forma del ojo del cliente, la condición de las pestañas naturales y el look deseado antes de crear un mapa. Documenta el mapa para consistencia durante los rellenos.</p>"),
    ],
    questions: [
      q(1,"MCQ","How many lashes does the upper eyelid typically have?","¿Cuántas pestañas tiene típicamente el párpado superior?",["30–50","30–50","90–150","90–150","200–300","200–300","500+","500+"],"b","The upper eyelid typically has 90–150 natural lashes arranged in 5–6 rows.","El párpado superior tiene típicamente 90–150 pestañas naturales dispuestas en 5–6 filas."),
      q(2,"MCQ","Which phase of the lash growth cycle is best for extension application?","¿Qué fase del ciclo de crecimiento es mejor para aplicar extensiones?",["Anagen","Anágena","Catagen","Catágena","Telogen","Telógena","Exogen","Exógena"],"b","Catagen is ideal because the lash is at or near full length and is stable.","La catágena es ideal porque la pestaña está en o cerca de su longitud completa y es estable."),
      q(3,"MCQ","What does 'C curl' refer to in lash extensions?","¿A qué se refiere 'curvatura C' en extensiones de pestañas?",["The thinnest diameter","El diámetro más delgado","The most popular balanced curl type","El tipo de curvatura equilibrada más popular","A flat-base curl for hooded eyes","Una curvatura de base plana para ojos encapotados","The longest available length","La longitud más larga disponible"],"b","C curl is the most commonly requested curl that provides a balanced, noticeable lift.","La curvatura C es la más solicitada que proporciona un levantamiento equilibrado y notable."),
      q(4,"MCQ","What is the golden rule for extension length relative to the natural lash?","¿Cuál es la regla de oro para la longitud de la extensión respecto a la pestaña natural?",["No more than 1mm longer","No más de 1mm más larga","No more than 3mm longer","No más de 3mm más larga","No more than 5mm longer","No más de 5mm más larga","No more than 10mm longer","No más de 10mm más larga"],"b","Extensions should never be more than 3mm longer than the natural lash to prevent damage.","Las extensiones nunca deben ser más de 3mm más largas que la pestaña natural para prevenir daños."),
      q(5,"MCQ","How many natural lashes typically shed per eye per day?","¿Cuántas pestañas naturales se caen por ojo por día típicamente?",["0","0","1–5","1–5","10–15","10–15","20+","20+"],"b","Natural shedding of 1–5 lashes per day per eye is completely normal as part of the growth cycle.","La caída natural de 1–5 pestañas por día por ojo es completamente normal como parte del ciclo de crecimiento."),
      q(6,"MCQ","What material are most modern lash extensions made of?","¿De qué material están hechas la mayoría de las extensiones modernas?",["Real mink fur","Piel de visón real","PBT synthetic fiber","Fibra sintética PBT","Human hair","Cabello humano","Nylon","Nailon"],"b","PBT (polybutylene terephthalate) is the industry standard, marketed under names like mink, silk, or synthetic.","PBT (tereftalato de polibutileno) es el estándar de la industria, comercializado bajo nombres como mink, seda o sintético."),
      q(7,"MCQ","Which eye shape benefits most from L or L+ curl extensions?","¿Qué forma de ojo se beneficia más de extensiones con curvatura L o L+?",["Round eyes","Ojos redondos","Hooded eyes","Ojos encapotados","Wide-set eyes","Ojos separados","Almond eyes","Ojos almendrados"],"b","L/L+ curls have a flat base with a sharp lift, making them ideal for hooded or monolid eyes.","Las curvaturas L/L+ tienen una base plana con un levantamiento pronunciado, ideales para ojos encapotados o monopárpado."),
      q(8,"SCENARIO","What should you recommend?","¿Qué deberías recomendar?",["Apply thicker extensions to cover gaps","Aplicar extensiones más gruesas para cubrir espacios","Recommend a lash break and use a recovery serum","Recomendar un descanso de pestañas y usar suero de recuperación","Use more adhesive for better retention","Usar más adhesivo para mejor retención","Switch to a different curl type","Cambiar a un tipo de curvatura diferente"],"b","When natural lashes show signs of damage, the responsible approach is to recommend a break and recovery.","Cuando las pestañas naturales muestran signos de daño, el enfoque responsable es recomendar un descanso y recuperación.","A client returns for a fill and you notice her natural lashes have become noticeably shorter with gaps in the lash line since her last appointment.","Una clienta regresa para un relleno y notas que sus pestañas naturales se han vuelto notablemente más cortas con espacios en la línea de pestañas desde su última cita."),
      q(9,"SCENARIO","Which lash map is most appropriate?","¿Qué mapa de pestañas es más apropiado?",["Longest lengths at inner corners to open the eye","Longitudes más largas en esquinas internas para abrir el ojo","Cat eye with longest lengths at outer corners","Ojo de gato con longitudes más largas en esquinas externas","Doll eye with longest lengths at center","Ojo de muñeca con longitudes más largas en el centro","Uniform length across all sections","Longitud uniforme en todas las secciones"],"c","For round eyes wanting a natural look, a doll eye map with longest lengths at center and shorter at corners creates a balanced, flattering effect.","Para ojos redondos que buscan un look natural, un mapa de ojo de muñeca con longitudes más largas en el centro y más cortas en las esquinas crea un efecto equilibrado y favorecedor.","A new client with round eyes requests a natural-looking lash set. She wants her eyes to appear more elongated and balanced.","Una nueva clienta con ojos redondos solicita un set de pestañas de aspecto natural. Quiere que sus ojos parezcan más alargados y equilibrados."),
      q(10,"SCENARIO","What is the best approach?","¿Cuál es el mejor enfoque?",["Apply the same extensions to all lashes","Aplicar las mismas extensiones a todas las pestañas","Skip baby lashes entirely","Saltar las pestañas bebé por completo","Use lighter/shorter extensions on baby lashes and appropriate weight on mature lashes","Usar extensiones más ligeras/cortas en pestañas bebé y peso apropiado en pestañas maduras","Only apply extensions to the longest lashes","Solo aplicar extensiones a las pestañas más largas"],"c","Different lashes in different growth phases require different extension weights. Baby lashes need lighter extensions.","Las pestañas en diferentes fases de crecimiento requieren diferentes pesos de extensión. Las pestañas bebé necesitan extensiones más ligeras.","During a full set application, you notice that the client has many baby lashes (anagen phase) mixed with mature lashes. She wants a full, dramatic look.","Durante una aplicación de set completo, notas que la clienta tiene muchas pestañas bebé (fase anágena) mezcladas con pestañas maduras. Ella quiere un look completo y dramático."),
    ],
  },

  // ────────────── MODULE 2 ──────────────
  {
    order: 2, isBonus: false,
    titleEn: "Sanitation, Safety & Professional Standards",
    titleEs: "Saneamiento, Seguridad y Estándares Profesionales",
    subtitleEn: "Protecting yourself and your clients",
    subtitleEs: "Protegiendo a ti misma y a tus clientes",
    quizTitleEn: "Sanitation & Safety Quiz",
    quizTitleEs: "Examen de Saneamiento y Seguridad",
    lessons: [
      lesson(1,"Sanitation & Disinfection Procedures","Procedimientos de Saneamiento y Desinfección","<p>Proper sanitation is non-negotiable in lash services. <strong>Disinfection vs. sterilization:</strong> Disinfection kills most pathogens on surfaces and tools; sterilization eliminates all microorganisms. Lash tools require high-level disinfection at minimum.</p><p>Use hospital-grade disinfectant on all non-disposable tools. Tweezers must be cleaned between each client using an approved disinfectant solution with a minimum contact time. Disposable items (micro brushes, lip wands, eye pads) should <strong>never</strong> be reused.</p><p>Your workstation surfaces must be wiped down between each client with a disinfectant spray. Use a fresh towel or disposable bed cover for each appointment.</p>","<p>El saneamiento adecuado no es negociable en los servicios de pestañas. <strong>Desinfección vs. esterilización:</strong> La desinfección mata la mayoría de los patógenos en superficies y herramientas; la esterilización elimina todos los microorganismos. Las herramientas de pestañas requieren desinfección de alto nivel como mínimo.</p><p>Usa desinfectante de grado hospitalario en todas las herramientas no desechables. Las pinzas deben limpiarse entre cada cliente usando una solución desinfectante aprobada con un tiempo de contacto mínimo. Los artículos desechables (micro cepillos, varitas labiales, parches para ojos) <strong>nunca</strong> deben reutilizarse.</p><p>Las superficies de tu estación de trabajo deben limpiarse entre cada cliente con un spray desinfectante. Usa una toalla fresca o cubierta desechable para la cama en cada cita.</p>"),
      lesson(2,"Hygiene for Tools, Hands & Workspace","Higiene para Herramientas, Manos y Espacio de Trabajo","<p><strong>Hand hygiene</strong> is your first line of defense. Wash hands thoroughly with soap and water for at least 20 seconds before and after each client. Apply hand sanitizer (60%+ alcohol) if soap and water aren't immediately available.</p><p>All reusable tools should follow a cleaning protocol: <strong>clean → disinfect → dry → store</strong> in a sealed container. Never store used and clean tools together. Label containers clearly.</p><p>Your workspace should be well-ventilated (adhesive fumes), well-lit, and organized. Keep adhesive stored upright in an airtight container. Replace adhesive every 4–6 weeks after opening.</p>","<p><strong>La higiene de manos</strong> es tu primera línea de defensa. Lava las manos minuciosamente con jabón y agua durante al menos 20 segundos antes y después de cada cliente. Aplica desinfectante de manos (60%+ alcohol) si el jabón y agua no están disponibles inmediatamente.</p><p>Todas las herramientas reutilizables deben seguir un protocolo de limpieza: <strong>limpiar → desinfectar → secar → almacenar</strong> en un contenedor sellado. Nunca almacenes herramientas usadas y limpias juntas. Etiqueta los contenedores claramente.</p><p>Tu espacio de trabajo debe estar bien ventilado (vapores del adhesivo), bien iluminado y organizado. Mantén el adhesivo almacenado en posición vertical en un contenedor hermético. Reemplaza el adhesivo cada 4–6 semanas después de abrirlo.</p>"),
      lesson(3,"Contraindications & Client Screening","Contraindicaciones y Evaluación del Cliente","<p>Before any lash service, you must screen clients for <strong>contraindications</strong> — conditions that make lash extensions unsafe.</p><p><strong>Absolute contraindications</strong> (do not apply): active eye infections (conjunctivitis, styes, blepharitis), chemotherapy, trichotillomania, severe allergies to cyanoacrylate, recent eye surgery (within 3 months).</p><p><strong>Relative contraindications</strong> (proceed with caution): dry eye syndrome, eczema around eyes, pregnancy (increased sensitivity), contact lens wearers (remove during service), alopecia. Always have clients complete a consultation form and sign a waiver before their first appointment.</p>","<p>Antes de cualquier servicio de pestañas, debes evaluar a los clientes para <strong>contraindicaciones</strong> — condiciones que hacen que las extensiones de pestañas no sean seguras.</p><p><strong>Contraindicaciones absolutas</strong> (no aplicar): infecciones oculares activas (conjuntivitis, orzuelos, blefaritis), quimioterapia, tricotilomanía, alergias severas al cianoacrilato, cirugía ocular reciente (dentro de 3 meses).</p><p><strong>Contraindicaciones relativas</strong> (proceder con precaución): síndrome de ojo seco, eccema alrededor de los ojos, embarazo (mayor sensibilidad), usuarios de lentes de contacto (retirar durante el servicio), alopecia. Siempre haz que los clientes completen un formulario de consulta y firmen una exención antes de su primera cita.</p>"),
      lesson(4,"Allergies, Irritation & Safety Prevention","Alergias, Irritación y Prevención de Seguridad","<p>The most common allergen in lash services is <strong>cyanoacrylate</strong>, the base ingredient in lash adhesive. True allergic reactions cause swelling, redness, itching, and can worsen with repeated exposure.</p><p><strong>Irritation vs. Allergy:</strong> Irritation is caused by fumes and usually resolves within 24–48 hours. Allergic reactions worsen over time and may involve the entire eye area. A patch test (applying 5–10 extensions 24–48 hours before a full set) can help identify allergic clients.</p><p>If a client has a reaction: advise them to take antihistamines, apply cold compresses, and see a doctor if severe. You should remove the extensions if the client returns. Never diagnose — always refer to a medical professional.</p>","<p>El alérgeno más común en los servicios de pestañas es el <strong>cianoacrilato</strong>, el ingrediente base del adhesivo de pestañas. Las reacciones alérgicas verdaderas causan hinchazón, enrojecimiento, picazón y pueden empeorar con la exposición repetida.</p><p><strong>Irritación vs. Alergia:</strong> La irritación es causada por los vapores y generalmente se resuelve dentro de 24–48 horas. Las reacciones alérgicas empeoran con el tiempo y pueden involucrar toda el área del ojo. Una prueba de parche (aplicar 5–10 extensiones 24–48 horas antes de un set completo) puede ayudar a identificar clientes alérgicos.</p><p>Si un cliente tiene una reacción: aconséjale que tome antihistamínicos, aplique compresas frías y consulte a un médico si es severa. Debes remover las extensiones si el cliente regresa. Nunca diagnostiques — siempre refiere a un profesional médico.</p>"),
      lesson(5,"Professional Conduct & Liability","Conducta Profesional y Responsabilidad","<p>As a lash professional, you represent yourself, your brand, and the industry. <strong>Professional conduct</strong> includes: punctuality, clear communication, maintaining client confidentiality, and continuing education.</p><p><strong>Liability protection:</strong> Carry professional liability insurance. Have clients sign informed consent forms. Document all services, products used, and any reactions. Keep records for at least 3 years.</p><p>Follow your state/country regulations regarding lash licensing requirements. Some jurisdictions require a cosmetology or esthetician license; others have specific lash certification requirements.</p>","<p>Como profesional de pestañas, te representas a ti misma, a tu marca y a la industria. <strong>La conducta profesional</strong> incluye: puntualidad, comunicación clara, mantener la confidencialidad del cliente y educación continua.</p><p><strong>Protección de responsabilidad:</strong> Ten seguro de responsabilidad profesional. Haz que los clientes firmen formularios de consentimiento informado. Documenta todos los servicios, productos utilizados y cualquier reacción. Guarda registros por al menos 3 años.</p><p>Sigue las regulaciones de tu estado/país con respecto a los requisitos de licencia de pestañas. Algunas jurisdicciones requieren una licencia de cosmetología o estética; otras tienen requisitos específicos de certificación de pestañas.</p>"),
    ],
    questions: [
      q(1,"MCQ","How long should you wash your hands before a lash appointment?","¿Cuánto tiempo debes lavarte las manos antes de una cita de pestañas?",["5 seconds","5 segundos","At least 20 seconds","Al menos 20 segundos","1 minute","1 minuto","It doesn't matter","No importa"],"b","CDC guidelines recommend washing hands for at least 20 seconds with soap and water.","Las pautas del CDC recomiendan lavarse las manos durante al menos 20 segundos con jabón y agua."),
      q(2,"MCQ","Which of the following is an absolute contraindication for lash extensions?","¿Cuál de las siguientes es una contraindicación absoluta para extensiones de pestañas?",["Wearing contact lenses","Usar lentes de contacto","Active conjunctivitis","Conjuntivitis activa","Dry skin","Piel seca","Previous lash tinting","Tinte de pestañas previo"],"b","Active eye infections like conjunctivitis are absolute contraindications — lashes should not be applied.","Las infecciones oculares activas como la conjuntivitis son contraindicaciones absolutas — no se deben aplicar pestañas."),
      q(3,"MCQ","What is the main allergen in lash adhesive?","¿Cuál es el principal alérgeno en el adhesivo de pestañas?",["Latex","Látex","Cyanoacrylate","Cianoacrilato","Formaldehyde","Formaldehído","Carbon black","Negro de carbono"],"b","Cyanoacrylate is the base ingredient in lash adhesives and the most common cause of allergic reactions.","El cianoacrilato es el ingrediente base de los adhesivos de pestañas y la causa más común de reacciones alérgicas."),
      q(4,"MCQ","How often should opened lash adhesive be replaced?","¿Con qué frecuencia se debe reemplazar el adhesivo de pestañas abierto?",["Every week","Cada semana","Every 4–6 weeks","Cada 4–6 semanas","Every 6 months","Cada 6 meses","Only when it runs out","Solo cuando se acaba"],"b","Adhesive degrades after opening. Replace every 4–6 weeks for optimal bonding performance.","El adhesivo se degrada después de abrirse. Reemplázalo cada 4–6 semanas para un rendimiento óptimo de adhesión."),
      q(5,"MCQ","What is the correct tool cleaning protocol order?","¿Cuál es el orden correcto del protocolo de limpieza de herramientas?",["Disinfect → Clean → Store → Dry","Desinfectar → Limpiar → Almacenar → Secar","Clean → Disinfect → Dry → Store","Limpiar → Desinfectar → Secar → Almacenar","Store → Clean → Disinfect → Dry","Almacenar → Limpiar → Desinfectar → Secar","Dry → Store → Clean → Disinfect","Secar → Almacenar → Limpiar → Desinfectar"],"b","The proper sequence is: clean debris off, disinfect, allow to dry, then store in a sealed container.","La secuencia correcta es: limpiar residuos, desinfectar, dejar secar, luego almacenar en un contenedor sellado."),
      q(6,"MCQ","How long should you wait after eye surgery before applying lash extensions?","¿Cuánto tiempo debes esperar después de una cirugía ocular antes de aplicar extensiones?",["1 week","1 semana","1 month","1 mes","At least 3 months","Al menos 3 meses","No waiting needed","No se necesita espera"],"c","A minimum of 3 months post-eye surgery is recommended before applying lash extensions.","Se recomienda un mínimo de 3 meses después de cirugía ocular antes de aplicar extensiones de pestañas."),
      q(7,"MCQ","What purpose does a patch test serve?","¿Qué propósito tiene una prueba de parche?",["To test adhesive speed","Para probar la velocidad del adhesivo","To identify allergic reactions before a full set","Para identificar reacciones alérgicas antes de un set completo","To practice lash application","Para practicar la aplicación de pestañas","To test different curl types","Para probar diferentes tipos de curvatura"],"b","A patch test applies a few extensions 24–48 hours before a full set to check for allergic reactions.","Una prueba de parche aplica unas pocas extensiones 24–48 horas antes de un set completo para verificar reacciones alérgicas."),
      q(8,"SCENARIO","What should you do?","¿Qué deberías hacer?",["Continue with the appointment and monitor","Continuar con la cita y monitorear","Politely decline service and refer to a doctor","Rechazar cortésmente el servicio y referir a un médico","Apply extensions only to the unaffected eye","Aplicar extensiones solo al ojo no afectado","Use a hypoallergenic adhesive instead","Usar un adhesivo hipoalergénico en su lugar"],"b","Active eye infections are absolute contraindications. You must decline service and refer to a medical professional.","Las infecciones oculares activas son contraindicaciones absolutas. Debes rechazar el servicio y referir a un profesional médico.","A client arrives for a full set appointment. During the consultation, you notice one of her eyes is red, slightly swollen, and has a yellowish discharge.","Una clienta llega para una cita de set completo. Durante la consulta, notas que uno de sus ojos está rojo, ligeramente hinchado y tiene una secreción amarillenta."),
      q(9,"SCENARIO","How do you differentiate between irritation and allergy?","¿Cómo diferencias entre irritación y alergia?",["Irritation appears immediately; allergy takes weeks","La irritación aparece inmediatamente; la alergia toma semanas","Irritation typically resolves in 24–48 hours; allergic reactions worsen over time","La irritación generalmente se resuelve en 24–48 horas; las reacciones alérgicas empeoran con el tiempo","They are the same thing","Son lo mismo","Allergies only affect one eye","Las alergias solo afectan un ojo"],"b","Irritation from fumes usually resolves within 24–48 hours, while true allergic reactions persist and worsen with repeated exposure.","La irritación por vapores generalmente se resuelve dentro de 24–48 horas, mientras que las reacciones alérgicas verdaderas persisten y empeoran con la exposición repetida.","A client calls you 24 hours after her first lash appointment saying her eyes feel slightly puffy and irritated. She asks if she's having an allergic reaction.","Una clienta te llama 24 horas después de su primera cita de pestañas diciendo que sus ojos se sienten ligeramente hinchados e irritados. Pregunta si está teniendo una reacción alérgica."),
      q(10,"SCENARIO","What is the most important action?","¿Cuál es la acción más importante?",["Apologize and offer a free service","Disculparse y ofrecer un servicio gratuito","Document everything and advise the client to seek medical attention","Documentar todo y aconsejar al cliente que busque atención médica","Blame the client's aftercare","Culpar al cuidado posterior del cliente","Ignore the complaint","Ignorar la queja"],"b","Documentation protects both you and the client. Always advise medical attention for concerning reactions and document thoroughly.","La documentación te protege a ti y al cliente. Siempre aconseja atención médica para reacciones preocupantes y documenta minuciosamente.","A regular client sends you photos showing significant swelling around both eyes 3 days after her fill appointment. She says it's getting worse, not better.","Una clienta regular te envía fotos mostrando hinchazón significativa alrededor de ambos ojos 3 días después de su cita de relleno. Dice que está empeorando, no mejorando."),
    ],
  },

  // ────────────── MODULE 3 ──────────────
  {
    order: 3, isBonus: false,
    titleEn: "Products & Tools",
    titleEs: "Productos y Herramientas",
    subtitleEn: "Know your professional toolkit",
    subtitleEs: "Conoce tu kit de herramientas profesional",
    quizTitleEn: "Products & Tools Quiz",
    quizTitleEs: "Examen de Productos y Herramientas",
    lessons: [
      lesson(1,"Tweezers: Types & Proper Use","Pinzas: Tipos y Uso Correcto","<p>Tweezers are your most important tools. The two primary types are <strong>isolation tweezers</strong> (straight or curved, used to separate natural lashes) and <strong>application tweezers</strong> (angled or volume, used to pick up and place extensions).</p><p><strong>Straight tweezers</strong> are best for isolation. <strong>Curved tweezers</strong> provide versatility. <strong>L-shaped/boot tweezers</strong> are excellent for volume fan pickup. <strong>Volume tweezers</strong> (45° angle) are designed specifically for making and picking up fans.</p><p>Quality matters — invest in precision-made, hand-tested tweezers. Keep them clean and never drop them, as this can misalign the tips and ruin their precision.</p>","<p>Las pinzas son tus herramientas más importantes. Los dos tipos principales son <strong>pinzas de aislamiento</strong> (rectas o curvas, usadas para separar pestañas naturales) y <strong>pinzas de aplicación</strong> (anguladas o de volumen, usadas para recoger y colocar extensiones).</p><p><strong>Las pinzas rectas</strong> son mejores para aislamiento. <strong>Las pinzas curvas</strong> proporcionan versatilidad. <strong>Las pinzas en forma de L/bota</strong> son excelentes para recoger abanicos de volumen. <strong>Las pinzas de volumen</strong> (ángulo de 45°) están diseñadas específicamente para hacer y recoger abanicos.</p><p>La calidad importa — invierte en pinzas de precisión probadas a mano. Mantenlas limpias y nunca las dejes caer, ya que esto puede desalinear las puntas y arruinar su precisión.</p>"),
      lesson(2,"Lash Adhesives","Adhesivos de Pestañas","<p>Lash adhesive is a <strong>cyanoacrylate-based</strong> glue that bonds extensions to natural lashes. Key factors affecting adhesive performance:</p><p><strong>Humidity:</strong> Most adhesives cure best at 45–60% relative humidity. Too low = slow curing, too high = shock polymerization (white residue). Use a hygrometer to monitor. <strong>Temperature:</strong> Optimal range is 68–72°F (20–22°C). <strong>Drying time:</strong> Ranges from 0.5 seconds (fast-dry, for experienced artists) to 2+ seconds (beginner-friendly).</p><p>Store adhesive upright in an airtight container with silica gel packets. Shake well before use. Dispense a fresh drop every 15–20 minutes. Replace 4–6 weeks after opening.</p>","<p>El adhesivo de pestañas es un <strong>pegamento a base de cianoacrilato</strong> que une las extensiones a las pestañas naturales. Factores clave que afectan el rendimiento del adhesivo:</p><p><strong>Humedad:</strong> La mayoría de los adhesivos curan mejor a 45–60% de humedad relativa. Muy baja = curado lento, muy alta = polimerización por choque (residuo blanco). Usa un higrómetro para monitorear. <strong>Temperatura:</strong> El rango óptimo es 68–72°F (20–22°C). <strong>Tiempo de secado:</strong> Varía de 0.5 segundos (secado rápido, para artistas experimentados) a 2+ segundos (amigable para principiantes).</p><p>Almacena el adhesivo en posición vertical en un contenedor hermético con paquetes de gel de sílice. Agita bien antes de usar. Dispensa una gota fresca cada 15–20 minutos. Reemplaza 4–6 semanas después de abrir.</p>"),
      lesson(3,"Lash Trays & Extension Selection","Bandejas de Pestañas y Selección de Extensiones","<p>Lash trays come in <strong>single-length trays</strong> (one length per strip) and <strong>mixed-length trays</strong> (multiple lengths on one strip). Mixed trays are convenient for beginners; single-length trays allow more precise selection.</p><p>When selecting extensions, consider: the client's natural lash strength, desired look, and lifestyle. A safe starting point for classic lashes: <strong>0.15mm diameter, C curl, 9–12mm length range</strong>.</p><p>Premium trays feature consistent curl, easy fan-off strips, and minimal curl variation. Invest in quality — inconsistent trays waste time and produce inferior results.</p>","<p>Las bandejas de pestañas vienen en <strong>bandejas de una sola longitud</strong> (una longitud por tira) y <strong>bandejas de longitudes mixtas</strong> (múltiples longitudes en una tira). Las bandejas mixtas son convenientes para principiantes; las de una sola longitud permiten una selección más precisa.</p><p>Al seleccionar extensiones, considera: la fuerza de la pestaña natural del cliente, el look deseado y el estilo de vida. Un punto de partida seguro para pestañas clásicas: <strong>diámetro de 0.15mm, curvatura C, rango de longitud de 9–12mm</strong>.</p><p>Las bandejas premium presentan curvatura consistente, tiras de fácil desprendimiento y variación mínima de curvatura. Invierte en calidad — las bandejas inconsistentes desperdician tiempo y producen resultados inferiores.</p>"),
      lesson(4,"Primers, Bonders & Removers","Imprimadores, Selladores y Removedores","<p><strong>Primer:</strong> Applied to natural lashes before extensions to remove oils and residue, optimizing adhesive bonding. Use sparingly — too much can interfere with the adhesive.</p><p><strong>Bonder/Superbonder:</strong> Applied to the adhesive bond after placement to instantly cure the adhesive, reduce fumes, and increase flexibility. This has become an essential step in modern lash application.</p><p><strong>Removers:</strong> Gel remover (for targeted removal of individual extensions) and cream remover (for full set removal). Never use oil-based removers near open eyes. Always protect the under-eye area during removal.</p>","<p><strong>Imprimador:</strong> Se aplica a las pestañas naturales antes de las extensiones para eliminar aceites y residuos, optimizando la adhesión. Usa con moderación — demasiado puede interferir con el adhesivo.</p><p><strong>Sellador/Superbonder:</strong> Se aplica al punto de adhesión después de la colocación para curar instantáneamente el adhesivo, reducir vapores y aumentar la flexibilidad. Esto se ha convertido en un paso esencial en la aplicación moderna de pestañas.</p><p><strong>Removedores:</strong> Removedor en gel (para remoción dirigida de extensiones individuales) y removedor en crema (para remoción de set completo). Nunca uses removedores a base de aceite cerca de los ojos abiertos. Siempre protege el área debajo del ojo durante la remoción.</p>"),
      lesson(5,"Lash Beds, Lighting, Tapes & Eye Pads","Camas de Pestañas, Iluminación, Cintas y Parches","<p>Your <strong>lash bed</strong> should be adjustable in height and recline angle. Memory foam toppers and neck pillows improve client comfort during 1–3 hour appointments.</p><p><strong>Lighting:</strong> A ring light or LED magnifying lamp is essential. Position it to eliminate shadows on the lash line. Color temperature of 5000–6500K provides the most accurate color rendering.</p><p><strong>Under-eye pads</strong> protect the lower lashes and skin during application. Gel pads are most comfortable; medical tape can supplement. Ensure pads don't press on the eyeball or cause the eye to open slightly during service. <strong>Micropore tape</strong> is used to lift the eyelid for better access to inner corners and to secure pads in place.</p>","<p>Tu <strong>cama de pestañas</strong> debe ser ajustable en altura y ángulo de reclinación. Los protectores de espuma viscoelástica y las almohadas para el cuello mejoran la comodidad del cliente durante las citas de 1–3 horas.</p><p><strong>Iluminación:</strong> Una luz anular o lámpara LED con lupa es esencial. Posiciónala para eliminar sombras en la línea de pestañas. Una temperatura de color de 5000–6500K proporciona la representación de color más precisa.</p><p><strong>Los parches debajo del ojo</strong> protegen las pestañas inferiores y la piel durante la aplicación. Los parches de gel son los más cómodos; la cinta médica puede complementar. Asegúrate de que los parches no presionen el globo ocular ni hagan que el ojo se abra ligeramente durante el servicio. <strong>La cinta micropore</strong> se usa para levantar el párpado para mejor acceso a las esquinas internas y para asegurar los parches en su lugar.</p>"),
    ],
    questions: [
      q(1,"MCQ","What type of tweezers is best for lash isolation?","¿Qué tipo de pinzas es mejor para el aislamiento de pestañas?",["Volume tweezers","Pinzas de volumen","Straight tweezers","Pinzas rectas","L-shaped tweezers","Pinzas en forma de L","Curved application tweezers","Pinzas de aplicación curvas"],"b","Straight tweezers provide the best control for isolating individual natural lashes.","Las pinzas rectas proporcionan el mejor control para aislar pestañas naturales individuales."),
      q(2,"MCQ","What is the optimal humidity range for most lash adhesives?","¿Cuál es el rango de humedad óptimo para la mayoría de los adhesivos?",["20–30%","20–30%","45–60%","45–60%","70–80%","70–80%","90–100%","90–100%"],"b","Most cyanoacrylate adhesives cure optimally between 45–60% relative humidity.","La mayoría de los adhesivos de cianoacrilato curan óptimamente entre 45–60% de humedad relativa."),
      q(3,"MCQ","What does a superbonder do?","¿Qué hace un superbonder?",["Removes extensions","Remueve extensiones","Instantly cures adhesive and reduces fumes","Cura instantáneamente el adhesivo y reduce vapores","Cleans natural lashes","Limpia las pestañas naturales","Changes adhesive color","Cambia el color del adhesivo"],"b","Superbonder instantly polymerizes the adhesive bond, reduces fumes, and increases flexibility.","El superbonder polimeriza instantáneamente el enlace adhesivo, reduce los vapores y aumenta la flexibilidad."),
      q(4,"MCQ","How often should you dispense a fresh adhesive drop during application?","¿Con qué frecuencia debes dispensar una gota fresca de adhesivo durante la aplicación?",["Every 5 minutes","Cada 5 minutos","Every 15–20 minutes","Cada 15–20 minutos","Every 45 minutes","Cada 45 minutos","Only at the beginning","Solo al principio"],"b","Adhesive begins to cure on the jade stone/glue ring. Fresh drops every 15–20 minutes ensure optimal bonding.","El adhesivo comienza a curar en la piedra de jade/anillo de pegamento. Gotas frescas cada 15–20 minutos aseguran una adhesión óptima."),
      q(5,"MCQ","What color temperature provides the most accurate lighting for lash work?","¿Qué temperatura de color proporciona la iluminación más precisa para trabajo de pestañas?",["2700K (warm)","2700K (cálida)","5000–6500K (daylight)","5000–6500K (luz del día)","8000K (cool blue)","8000K (azul frío)","Color doesn't matter","El color no importa"],"b","5000–6500K daylight temperature provides the most accurate color rendering for detail work.","La temperatura de luz del día de 5000–6500K proporciona la representación de color más precisa para trabajo detallado."),
      q(6,"MCQ","What is the safe starting diameter for classic lash extensions?","¿Cuál es el diámetro inicial seguro para extensiones de pestañas clásicas?",["0.03mm","0.03mm","0.15mm","0.15mm","0.25mm","0.25mm","0.30mm","0.30mm"],"b","0.15mm is a standard classic diameter that's safe for most natural lashes.","0.15mm es un diámetro clásico estándar que es seguro para la mayoría de las pestañas naturales."),
      q(7,"MCQ","What should you NEVER do with under-eye pads?","¿Qué NUNCA debes hacer con los parches debajo del ojo?",["Use gel pads","Usar parches de gel","Allow them to press on the eyeball","Permitir que presionen el globo ocular","Secure them with tape","Asegurarlos con cinta","Use fresh pads for each client","Usar parches nuevos para cada cliente"],"b","Pads pressing on the eyeball can cause discomfort and potentially damage the cornea.","Los parches que presionan el globo ocular pueden causar incomodidad y potencialmente dañar la córnea."),
      q(8,"SCENARIO","What is the likely cause?","¿Cuál es la causa probable?",["Bad extension quality","Mala calidad de extensiones","The humidity is too high, causing shock polymerization","La humedad es demasiado alta, causando polimerización por choque","The client is allergic","La clienta es alérgica","The tweezers are dirty","Las pinzas están sucias"],"b","White residue on the adhesive bond is a classic sign of shock polymerization caused by high humidity.","El residuo blanco en el enlace adhesivo es un signo clásico de polimerización por choque causada por alta humedad.","You notice white, chalky residue forming on the adhesive bonds shortly after placing each extension. The room feels warm and muggy.","Notas un residuo blanco y polvoriento formándose en los enlaces adhesivos poco después de colocar cada extensión. La habitación se siente cálida y húmeda."),
      q(9,"SCENARIO","What should you do?","¿Qué deberías hacer?",["Use the same drop and continue","Usar la misma gota y continuar","Stop, shake the adhesive well, dispense a new drop, and check humidity","Parar, agitar bien el adhesivo, dispensar una nueva gota y verificar la humedad","Add primer to the adhesive drop","Agregar imprimador a la gota de adhesivo","Switch to a different client","Cambiar a un cliente diferente"],"b","When adhesive becomes thick and stringy, it has started to polymerize. A fresh drop from a well-shaken bottle is needed.","Cuando el adhesivo se vuelve grueso e hilachento, ha comenzado a polimerizarse. Se necesita una gota fresca de una botella bien agitada."),
      q(10,"SCENARIO","What is the best solution?","¿Cuál es la mejor solución?",["Tell the client to deal with it","Decirle al cliente que lo soporte","Reposition the pad so it sits below the waterline without pressing on the eye","Reposicionar el parche para que se sitúe debajo de la línea de agua sin presionar el ojo","Remove the pad entirely","Remover el parche por completo","Use more tape to hold it tighter","Usar más cinta para sostenerlo más fuerte"],"b","The pad needs repositioning — it should protect the lower lashes without pressing the eyeball or causing the eye to gap open.","El parche necesita reposicionamiento — debe proteger las pestañas inferiores sin presionar el globo ocular ni hacer que el ojo se abra.","During application, your client complains that she can slightly see through her closed eye on one side. You notice the under-eye pad has shifted upward.","Durante la aplicación, tu clienta se queja de que puede ver ligeramente a través de su ojo cerrado en un lado. Notas que el parche debajo del ojo se ha desplazado hacia arriba."),
    ],
  },

  // ────────────── MODULE 4 ──────────────
  {
    order: 4, isBonus: false,
    titleEn: "Classic Lash Extensions",
    titleEs: "Extensiones de Pestañas Clásicas",
    subtitleEn: "Master one-to-one application",
    subtitleEs: "Domina la aplicación uno a uno",
    quizTitleEn: "Classic Lash Extensions Quiz",
    quizTitleEs: "Examen de Extensiones Clásicas",
    lessons: [
      lesson(1,"Isolation Techniques","Técnicas de Aislamiento","<p><strong>Isolation</strong> is the single most important skill in lash application. Each natural lash must be completely separated before an extension is applied. Poor isolation leads to stickies (two or more lashes bonded together), which cause discomfort, damage, and premature shedding.</p><p>Techniques: Use your non-dominant hand to hold isolation tweezers. Separate the target lash by gently pushing neighboring lashes away. Work systematically — inner to outer corner, or use the \"zigzag\" method (alternating sides to let adhesive cure).</p><p>Common isolation challenges: fine/sparse lashes, twisted lashes, baby lashes growing close together. Practice on a mannequin head until isolation becomes second nature.</p>","<p><strong>El aislamiento</strong> es la habilidad más importante en la aplicación de pestañas. Cada pestaña natural debe estar completamente separada antes de aplicar una extensión. Un mal aislamiento lleva a pegados (dos o más pestañas unidas), que causan incomodidad, daño y caída prematura.</p><p>Técnicas: Usa tu mano no dominante para sostener las pinzas de aislamiento. Separa la pestaña objetivo empujando suavemente las pestañas vecinas. Trabaja sistemáticamente — de esquina interna a externa, o usa el método \"zigzag\" (alternando lados para que el adhesivo cure).</p><p>Desafíos comunes de aislamiento: pestañas finas/escasas, pestañas torcidas, pestañas bebé creciendo juntas. Practica en una cabeza de maniquí hasta que el aislamiento se vuelva natural.</p>"),
      lesson(2,"Proper Attachment & Placement","Adhesión y Colocación Correcta","<p>The extension should be bonded to the natural lash <strong>1–2mm away from the eyelid</strong> — never touching the skin. The adhesive bond should wrap around the natural lash, not just sit on top.</p><p><strong>Proper placement:</strong> Dip 2–3mm of the extension base into adhesive. Place on the natural lash with the extension base sitting on top or to the side of the natural lash. The bond point should be smooth with no visible adhesive clumps.</p><p><strong>Direction matters:</strong> Extensions should follow the natural growth direction. Inner corner lashes angle inward, center lashes grow straight up, outer corner lashes angle outward. Placing against the natural direction causes twisting and discomfort.</p>","<p>La extensión debe unirse a la pestaña natural <strong>1–2mm alejada del párpado</strong> — nunca tocando la piel. El enlace adhesivo debe envolver la pestaña natural, no solo sentarse encima.</p><p><strong>Colocación correcta:</strong> Sumerge 2–3mm de la base de la extensión en adhesivo. Coloca sobre la pestaña natural con la base de la extensión sentada encima o al lado de la pestaña natural. El punto de unión debe ser suave sin grumos de adhesivo visibles.</p><p><strong>La dirección importa:</strong> Las extensiones deben seguir la dirección de crecimiento natural. Las pestañas de la esquina interna se inclinan hacia adentro, las del centro crecen hacia arriba, las de la esquina externa se inclinan hacia afuera. Colocar contra la dirección natural causa torsión e incomodidad.</p>"),
      lesson(3,"Weight Control & Natural Lash Protection","Control de Peso y Protección de Pestañas Naturales","<p>Every natural lash has a <strong>weight limit</strong> based on its thickness and growth phase. Exceeding this limit causes stress on the follicle, leading to premature shedding or permanent damage.</p><p>Guidelines: A fine natural lash (thin diameter) should only support a 0.10–0.12mm extension. A medium natural lash supports 0.12–0.15mm. A thick, healthy natural lash can handle 0.15–0.20mm. Never apply heavy extensions to baby lashes.</p><p>The <strong>length rule:</strong> Extensions should be no more than 3mm longer than the natural lash and no more than 1mm thicker in diameter. When in doubt, go lighter — client safety always comes first.</p>","<p>Cada pestaña natural tiene un <strong>límite de peso</strong> basado en su grosor y fase de crecimiento. Exceder este límite causa estrés en el folículo, llevando a caída prematura o daño permanente.</p><p>Directrices: Una pestaña natural fina (diámetro delgado) solo debe soportar una extensión de 0.10–0.12mm. Una pestaña natural media soporta 0.12–0.15mm. Una pestaña natural gruesa y saludable puede manejar 0.15–0.20mm. Nunca apliques extensiones pesadas a pestañas bebé.</p><p>La <strong>regla de longitud:</strong> Las extensiones no deben ser más de 3mm más largas que la pestaña natural ni más de 1mm más gruesas en diámetro. Cuando tengas dudas, ve más ligero — la seguridad del cliente siempre es primero.</p>"),
      lesson(4,"Classic Lash Mapping Styles","Estilos de Mapeo de Pestañas Clásicas","<p>Lash mapping creates a blueprint for your design before you start applying. Mark sections on the eye pad and assign lengths and curls to each zone.</p><p><strong>Popular classic maps:</strong> Natural (gradual increase to center, decrease to outer), Cat Eye (gradual increase toward outer corner), Doll Eye (longest at center, dramatic drop at corners), Open Eye (stronger curl and length at center to \"open\" the eye).</p><p>Tips: Always consider the client's eye shape, face structure, and lifestyle. A client who wears glasses may need shorter lengths. A client with downturned eyes benefits from a cat eye map with lifted outer corners.</p>","<p>El mapeo de pestañas crea un plano para tu diseño antes de comenzar a aplicar. Marca secciones en el parche del ojo y asigna longitudes y curvaturas a cada zona.</p><p><strong>Mapas clásicos populares:</strong> Natural (aumento gradual al centro, disminución al exterior), Ojo de Gato (aumento gradual hacia la esquina externa), Ojo de Muñeca (más largo en el centro, caída dramática en las esquinas), Ojo Abierto (curvatura y longitud más fuertes en el centro para \"abrir\" el ojo).</p><p>Consejos: Siempre considera la forma del ojo del cliente, la estructura facial y el estilo de vida. Un cliente que usa gafas puede necesitar longitudes más cortas. Un cliente con ojos caídos se beneficia de un mapa de ojo de gato con esquinas externas levantadas.</p>"),
      lesson(5,"Common Beginner Mistakes","Errores Comunes de Principiantes","<p>Learning from common mistakes accelerates your growth as a lash artist:</p><ul><li><strong>Poor isolation:</strong> Rushing leads to stickies. Slow down and verify each lash is isolated before applying.</li><li><strong>Too much adhesive:</strong> A thin layer is sufficient. Excess adhesive creates clumps and extends drying time.</li><li><strong>Wrong placement distance:</strong> Too close to the lid causes irritation; too far out causes the extension to droop.</li><li><strong>Ignoring natural lash health:</strong> Applying to damaged or baby lashes causes further harm.</li><li><strong>Not checking your work:</strong> Always review the set from multiple angles before the client leaves. Use a mirror to check for stickies, symmetry, and proper direction.</li></ul>","<p>Aprender de los errores comunes acelera tu crecimiento como artista de pestañas:</p><ul><li><strong>Mal aislamiento:</strong> Apurarse lleva a pegados. Ve más lento y verifica que cada pestaña esté aislada antes de aplicar.</li><li><strong>Demasiado adhesivo:</strong> Una capa delgada es suficiente. El exceso de adhesivo crea grumos y extiende el tiempo de secado.</li><li><strong>Distancia de colocación incorrecta:</strong> Muy cerca del párpado causa irritación; muy lejos causa que la extensión se caiga.</li><li><strong>Ignorar la salud de la pestaña natural:</strong> Aplicar a pestañas dañadas o bebé causa más daño.</li><li><strong>No revisar tu trabajo:</strong> Siempre revisa el set desde múltiples ángulos antes de que el cliente se vaya. Usa un espejo para verificar pegados, simetría y dirección correcta.</li></ul>"),
    ],
    questions: [
      q(1,"MCQ","How far from the eyelid should an extension be placed?","¿A qué distancia del párpado se debe colocar una extensión?",["Touching the skin","Tocando la piel","1–2mm from the eyelid","1–2mm del párpado","5mm from the eyelid","5mm del párpado","At the lash tip","En la punta de la pestaña"],"b","Extensions should be bonded 1–2mm from the eyelid — never touching the skin.","Las extensiones deben unirse a 1–2mm del párpado — nunca tocando la piel."),
      q(2,"MCQ","What is a 'sticky' in lash terminology?","¿Qué es un 'pegado' en terminología de pestañas?",["A well-bonded extension","Una extensión bien unida","Two or more lashes bonded together","Dos o más pestañas unidas juntas","An extension that fell off","Una extensión que se cayó","A type of adhesive","Un tipo de adhesivo"],"b","A sticky occurs when two or more natural lashes are bonded together, causing discomfort and damage.","Un pegado ocurre cuando dos o más pestañas naturales se unen juntas, causando incomodidad y daño."),
      q(3,"MCQ","Which lash mapping style features longest lengths at the outer corner?","¿Qué estilo de mapeo presenta las longitudes más largas en la esquina externa?",["Doll Eye","Ojo de Muñeca","Cat Eye","Ojo de Gato","Natural","Natural","Open Eye","Ojo Abierto"],"b","Cat Eye mapping uses a gradual increase toward the outer corner for an elongating effect.","El mapeo de Ojo de Gato usa un aumento gradual hacia la esquina externa para un efecto de alargamiento."),
      q(4,"MCQ","What diameter extension is appropriate for a fine natural lash?","¿Qué diámetro de extensión es apropiado para una pestaña natural fina?",["0.20mm","0.20mm","0.10–0.12mm","0.10–0.12mm","0.25mm","0.25mm","Any diameter is fine","Cualquier diámetro está bien"],"b","Fine natural lashes can only safely support 0.10–0.12mm diameter extensions.","Las pestañas naturales finas solo pueden soportar de forma segura extensiones de diámetro de 0.10–0.12mm."),
      q(5,"MCQ","How much adhesive should be applied to an extension base?","¿Cuánto adhesivo se debe aplicar a la base de una extensión?",["A large bead","Una gota grande","A thin coat on 2–3mm of the base","Una capa delgada en 2–3mm de la base","Cover the entire extension","Cubrir toda la extensión","No adhesive needed if using primer","No se necesita adhesivo si se usa imprimador"],"b","Dip 2–3mm of the extension base into adhesive for a thin, even coat — excess causes clumps.","Sumerge 2–3mm de la base de la extensión en adhesivo para una capa delgada y uniforme — el exceso causa grumos."),
      q(6,"MCQ","What is the 'zigzag method' in lash application?","¿Qué es el 'método zigzag' en la aplicación de pestañas?",["Applying extensions in a wave pattern","Aplicar extensiones en un patrón de onda","Alternating between left and right sides to let adhesive cure","Alternar entre el lado izquierdo y derecho para que el adhesivo cure","Using two types of curls","Usar dos tipos de curvaturas","A way to clean tweezers","Una forma de limpiar pinzas"],"b","The zigzag method alternates sides of the eye, giving adhesive time to cure before working on adjacent lashes.","El método zigzag alterna los lados del ojo, dando tiempo al adhesivo para curar antes de trabajar en pestañas adyacentes."),
      q(7,"MCQ","What should you always do before a client leaves?","¿Qué debes hacer siempre antes de que un cliente se vaya?",["Rush to the next client","Apurarse al siguiente cliente","Check for stickies, symmetry, and proper direction from multiple angles","Verificar pegados, simetría y dirección correcta desde múltiples ángulos","Apply extra adhesive","Aplicar adhesivo extra","Nothing special","Nada especial"],"b","Always review the completed set from multiple angles and use a mirror to verify quality.","Siempre revisa el set completado desde múltiples ángulos y usa un espejo para verificar la calidad."),
      q(8,"SCENARIO","What is the most likely cause of this discomfort?","¿Cuál es la causa más probable de esta incomodidad?",["She's allergic to the extensions","Es alérgica a las extensiones","Stickies — lashes are bonded together and pulling when she blinks","Pegados — las pestañas están unidas y tiran al parpadear","The extensions are too light","Las extensiones son demasiado ligeras","She slept wrong","Durmió en mala posición"],"b","Pulling and pinching sensations when blinking are classic signs of stickies where lashes are bonded together.","Las sensaciones de tirón y pellizco al parpadear son signos clásicos de pegados donde las pestañas están unidas.","A client calls the day after her appointment complaining of a pulling, pinching sensation when she blinks. She says it's only in one specific spot on her left eye.","Una clienta llama el día después de su cita quejándose de una sensación de tirón y pellizco al parpadear. Dice que es solo en un punto específico de su ojo izquierdo."),
      q(9,"SCENARIO","What extensions should you use?","¿Qué extensiones deberías usar?",["0.20mm D curl, 14mm — same as always","0.20mm curvatura D, 14mm — como siempre","0.15mm C curl, 8–11mm range for a natural look that fits under glasses","0.15mm curvatura C, rango de 8–11mm para un look natural que quepa bajo las gafas","0.25mm L curl, 15mm for maximum drama","0.25mm curvatura L, 15mm para máximo drama","Don't apply extensions if she wears glasses","No aplicar extensiones si usa gafas"],"b","Glasses-wearing clients need shorter lengths to avoid extensions hitting the lenses. Moderate curl and length work best.","Los clientes que usan gafas necesitan longitudes más cortas para evitar que las extensiones golpeen los lentes. Curvatura y longitud moderadas funcionan mejor.","A client wears thick-framed glasses daily and wants classic lashes. Her natural lashes are medium thickness and healthy. She wants a natural, everyday look.","Una clienta usa gafas de marco grueso diariamente y quiere pestañas clásicas. Sus pestañas naturales son de grosor medio y saludables. Quiere un look natural y cotidiano."),
      q(10,"SCENARIO","What is the best approach?","¿Cuál es el mejor enfoque?",["Apply extensions to every lash regardless","Aplicar extensiones a cada pestaña sin importar","Use lighter, thinner extensions (0.10mm) on the sparse area and normal on the other eye, adjusting to balance both sides","Usar extensiones más ligeras y delgadas (0.10mm) en el área escasa y normales en el otro ojo, ajustando para equilibrar ambos lados","Only lash the eye with more natural lashes","Solo aplicar pestañas al ojo con más pestañas naturales","Tell her you can't help","Decirle que no puedes ayudar"],"b","Asymmetry requires adapting your approach — lighter extensions on sparser areas and adjusting maps to create visual balance.","La asimetría requiere adaptar tu enfoque — extensiones más ligeras en áreas más escasas y ajustar mapas para crear equilibrio visual.","Your client has noticeably fewer natural lashes on her right eye compared to her left. She wants both eyes to look even and full.","Tu clienta tiene notablemente menos pestañas naturales en su ojo derecho comparado con el izquierdo. Quiere que ambos ojos se vean parejos y completos."),
    ],
  },

  // ────────────── MODULE 5 ──────────────
  {
    order: 5, isBonus: false,
    titleEn: "Volume & Hybrid Lashes",
    titleEs: "Pestañas de Volumen e Híbridas",
    subtitleEn: "Level up with fans and volume",
    subtitleEs: "Sube de nivel con abanicos y volumen",
    quizTitleEn: "Volume & Hybrid Quiz",
    quizTitleEs: "Examen de Volumen e Híbridas",
    lessons: [
      lesson(1,"Volume Theory & Lash Ratios","Teoría de Volumen y Proporciones","<p><strong>Volume lashing</strong> involves applying a fan of multiple thin extensions to a single natural lash. This creates fullness and density without excessive weight.</p><p>Volume extensions use thinner diameters: 0.03mm (mega volume, 10–16 lash fans), 0.05mm (standard volume, 5–8 fans), 0.07mm (light volume, 2–5 fans). The combined weight of a fan must not exceed what the natural lash can support.</p><p>The <strong>rule of 0.15:</strong> The combined diameter of your fan should approximate the weight of a single 0.15mm classic extension. For example: 5D × 0.05mm ≈ 0.15mm weight equivalent.</p>","<p><strong>Las pestañas de volumen</strong> implican aplicar un abanico de múltiples extensiones delgadas a una sola pestaña natural. Esto crea plenitud y densidad sin peso excesivo.</p><p>Las extensiones de volumen usan diámetros más delgados: 0.03mm (mega volumen, abanicos de 10–16 pestañas), 0.05mm (volumen estándar, abanicos de 5–8), 0.07mm (volumen ligero, abanicos de 2–5). El peso combinado de un abanico no debe exceder lo que la pestaña natural puede soportar.</p><p>La <strong>regla de 0.15:</strong> El diámetro combinado de tu abanico debe aproximar el peso de una sola extensión clásica de 0.15mm. Por ejemplo: 5D × 0.05mm ≈ equivalente de peso de 0.15mm.</p>"),
      lesson(2,"Fan Making: Handmade vs Premade","Hacer Abanicos: Hechos a Mano vs Prefabricados","<p><strong>Handmade fans</strong> are created by the artist during application using tweezers. Methods include: pinching (squeeze at the base), rolling (rolling between fingers on the strip), and the shimmy technique. Handmade fans offer more customization and typically have a thinner base.</p><p><strong>Premade fans</strong> (also called ProMade) come pre-bonded at the base. They save time but have a thicker base and less customization. They're a great starting point for artists learning volume.</p><p>Handmade fans are considered the gold standard in the industry because they're lighter, more customizable, and create a more natural-looking result.</p>","<p><strong>Los abanicos hechos a mano</strong> son creados por el artista durante la aplicación usando pinzas. Los métodos incluyen: pellizco (apretar en la base), rodamiento (rodar entre los dedos en la tira) y la técnica de movimiento. Los abanicos hechos a mano ofrecen más personalización y típicamente tienen una base más delgada.</p><p><strong>Los abanicos prefabricados</strong> (también llamados ProMade) vienen pre-unidos en la base. Ahorran tiempo pero tienen una base más gruesa y menos personalización. Son un gran punto de partida para artistas que aprenden volumen.</p><p>Los abanicos hechos a mano son considerados el estándar de oro en la industria porque son más ligeros, más personalizables y crean un resultado de aspecto más natural.</p>"),
      lesson(3,"Fan Control & Symmetry","Control de Abanicos y Simetría","<p><strong>Fan symmetry</strong> means each fan should have evenly spread extensions — no crossing, gaps, or uneven spacing. A well-made fan looks like a perfectly spread flower petal from above.</p><p>Key principles: consistent fan width (not too narrow or wide), even spacing between each extension in the fan, clean base with minimal adhesive, and proper wrapping around the natural lash.</p><p>Practice creates consistency. Work on making fans the same width and density. Use the same pressure and technique for each fan to build muscle memory. Aim for at least 200 practice fans before working on real clients.</p>","<p><strong>La simetría del abanico</strong> significa que cada abanico debe tener extensiones distribuidas uniformemente — sin cruce, espacios o separación desigual. Un abanico bien hecho se ve como un pétalo de flor perfectamente abierto desde arriba.</p><p>Principios clave: ancho de abanico consistente (ni muy estrecho ni muy ancho), espaciado uniforme entre cada extensión en el abanico, base limpia con adhesivo mínimo y envolvimiento correcto alrededor de la pestaña natural.</p><p>La práctica crea consistencia. Trabaja en hacer abanicos del mismo ancho y densidad. Usa la misma presión y técnica para cada abanico para construir memoria muscular. Apunta a al menos 200 abanicos de práctica antes de trabajar con clientes reales.</p>"),
      lesson(4,"Hybrid Lash Sets","Sets de Pestañas Híbridas","<p><strong>Hybrid lashes</strong> combine classic (1:1) and volume (1:many) techniques in a single set. The typical ratio is 30% classic / 70% volume or 50/50, creating a textured, multidimensional look.</p><p>Strategy: Place classic extensions on the strongest natural lashes and volume fans on finer lashes. This creates dimension while respecting each lash's weight limit. Hybrid sets are popular because they offer more fullness than classic but a more natural look than full volume.</p><p>Mapping for hybrids: Mark your lash map to indicate where classic and volume will go. Generally, use classic at inner corners (where natural lashes are finest) and volume throughout the center and outer sections.</p>","<p><strong>Las pestañas híbridas</strong> combinan técnicas clásicas (1:1) y de volumen (1:muchas) en un solo set. La proporción típica es 30% clásico / 70% volumen o 50/50, creando un look texturizado y multidimensional.</p><p>Estrategia: Coloca extensiones clásicas en las pestañas naturales más fuertes y abanicos de volumen en pestañas más finas. Esto crea dimensión respetando el límite de peso de cada pestaña. Los sets híbridos son populares porque ofrecen más plenitud que los clásicos pero un look más natural que el volumen completo.</p><p>Mapeo para híbridos: Marca tu mapa de pestañas para indicar dónde irán las clásicas y el volumen. Generalmente, usa clásicas en las esquinas internas (donde las pestañas naturales son más finas) y volumen en las secciones centrales y externas.</p>"),
      lesson(5,"Safe Volume Styling","Estilización Segura de Volumen","<p>Volume lashing requires extra attention to safety because multiple extensions share one natural lash. Key safety guidelines:</p><ul><li>Never exceed the natural lash's weight capacity — use the diameter/fan ratio calculator</li><li>Ensure the fan base is narrow and clean — a thick base adds unnecessary weight</li><li>Don't stack fans (placing one fan on top of another on the same lash)</li><li>Monitor retention closely — if fans are shedding quickly, the weight may be too heavy</li><li>Use superbonder to cure adhesive and reduce stress on the bond</li></ul><p>Mega volume (10–16D) should only be attempted by experienced artists on clients with strong, healthy natural lashes.</p>","<p>Las pestañas de volumen requieren atención extra a la seguridad porque múltiples extensiones comparten una pestaña natural. Directrices clave de seguridad:</p><ul><li>Nunca excedas la capacidad de peso de la pestaña natural — usa la calculadora de proporción diámetro/abanico</li><li>Asegúrate de que la base del abanico sea estrecha y limpia — una base gruesa agrega peso innecesario</li><li>No apiles abanicos (colocar un abanico encima de otro en la misma pestaña)</li><li>Monitorea la retención de cerca — si los abanicos se caen rápidamente, el peso puede ser demasiado</li><li>Usa superbonder para curar el adhesivo y reducir el estrés en la unión</li></ul><p>El mega volumen (10–16D) solo debe ser intentado por artistas experimentados en clientes con pestañas naturales fuertes y saludables.</p>"),
    ],
    questions: [
      q(1,"MCQ","What diameter is typically used for standard volume fans (5–8D)?","¿Qué diámetro se usa típicamente para abanicos de volumen estándar (5–8D)?",["0.15mm","0.15mm","0.05mm","0.05mm","0.20mm","0.20mm","0.10mm","0.10mm"],"b","0.05mm is the standard diameter for volume fans of 5–8 extensions.","0.05mm es el diámetro estándar para abanicos de volumen de 5–8 extensiones."),
      q(2,"MCQ","What is the 'rule of 0.15' in volume lashing?","¿Qué es la 'regla de 0.15' en pestañas de volumen?",["All extensions should be 0.15mm","Todas las extensiones deben ser de 0.15mm","The combined fan weight should approximate a single 0.15mm classic extension","El peso combinado del abanico debe aproximar una sola extensión clásica de 0.15mm","Apply 15 fans per eye","Aplicar 15 abanicos por ojo","Use 15mm length maximum","Usar máximo 15mm de longitud"],"b","The total weight of a volume fan should be equivalent to what a single 0.15mm classic extension weighs.","El peso total de un abanico de volumen debe ser equivalente a lo que pesa una sola extensión clásica de 0.15mm."),
      q(3,"MCQ","Why are handmade fans considered superior to premade?","¿Por qué se consideran superiores los abanicos hechos a mano a los prefabricados?",["They're cheaper","Son más baratos","They have a thinner base, less weight, and more customization","Tienen una base más delgada, menos peso y más personalización","They last longer","Duran más","They're faster to apply","Son más rápidos de aplicar"],"b","Handmade fans have thinner bases, offer more customization, and create lighter, more natural results.","Los abanicos hechos a mano tienen bases más delgadas, ofrecen más personalización y crean resultados más ligeros y naturales."),
      q(4,"MCQ","What is the typical ratio in a hybrid lash set?","¿Cuál es la proporción típica en un set de pestañas híbridas?",["100% classic","100% clásico","30% classic / 70% volume or 50/50","30% clásico / 70% volumen o 50/50","100% volume","100% volumen","10% classic / 90% volume","10% clásico / 90% volumen"],"b","Hybrid sets typically use 30/70 or 50/50 classic-to-volume ratio for a textured, dimensional look.","Los sets híbridos típicamente usan proporción 30/70 o 50/50 de clásico a volumen para un look texturizado y dimensional."),
      q(5,"MCQ","How many practice fans should you make before working on real clients?","¿Cuántos abanicos de práctica debes hacer antes de trabajar con clientes reales?",["10","10","At least 200","Al menos 200","50","50","None needed","No se necesitan"],"b","At least 200 practice fans builds the muscle memory needed for consistent, quality results.","Al menos 200 abanicos de práctica construyen la memoria muscular necesaria para resultados consistentes y de calidad."),
      q(6,"MCQ","Where should classic extensions typically go in a hybrid set?","¿Dónde deben ir típicamente las extensiones clásicas en un set híbrido?",["Only at the outer corner","Solo en la esquina externa","At the inner corners where natural lashes are finest","En las esquinas internas donde las pestañas naturales son más finas","Randomly throughout","Aleatoriamente en todo el set","Only at the center","Solo en el centro"],"b","Inner corner lashes are typically finest, making them better suited for lighter classic extensions.","Las pestañas de la esquina interna son típicamente las más finas, haciéndolas más adecuadas para extensiones clásicas más ligeras."),
      q(7,"MCQ","What is 'fan stacking' and why is it dangerous?","¿Qué es 'apilar abanicos' y por qué es peligroso?",["Organizing fans on your tile","Organizar abanicos en tu loseta","Placing multiple fans on one natural lash, which overloads it with weight","Colocar múltiples abanicos en una pestaña natural, sobrecargándola con peso","Making fans ahead of time","Hacer abanicos con anticipación","Using fans of different sizes","Usar abanicos de diferentes tamaños"],"b","Stacking fans on a single lash doubles or triples the weight, causing potential damage to the natural lash.","Apilar abanicos en una sola pestaña duplica o triplica el peso, causando posible daño a la pestaña natural."),
      q(8,"SCENARIO","What is the issue?","¿Cuál es el problema?",["The client's lashes are unhealthy","Las pestañas de la clienta son poco saludables","The fans are too narrow — they need wider spread for even coverage","Los abanicos son demasiado estrechos — necesitan una apertura más amplia para cobertura uniforme","The adhesive is bad","El adhesivo está malo","The lighting is wrong","La iluminación está mal"],"b","Narrow, closed fans create a spiky look. Wider, evenly spread fans provide the fluffy fullness volume sets are known for.","Los abanicos estrechos y cerrados crean un look puntiagudo. Los abanicos más anchos y uniformemente abiertos proporcionan la plenitud esponjosa por la que son conocidos los sets de volumen."),
      q(9,"SCENARIO","What is your recommended approach?","¿Cuál es tu enfoque recomendado?",["Full mega volume for maximum drama","Mega volumen completo para máximo drama","A hybrid set with classic on her fine lashes and light volume (3–4D with 0.07mm) on stronger lashes","Un set híbrido con clásicas en sus pestañas finas y volumen ligero (3–4D con 0.07mm) en pestañas más fuertes","Decline the service","Rechazar el servicio","Only classic with thick extensions","Solo clásicas con extensiones gruesas"],"b","For fine natural lashes wanting volume, a hybrid approach with light fans respects lash health while adding fullness.","Para pestañas naturales finas que buscan volumen, un enfoque híbrido con abanicos ligeros respeta la salud de las pestañas mientras agrega plenitud.","A client with fine, sparse natural lashes wants a full, voluminous look for her wedding. She's never had lash extensions before.","Una clienta con pestañas naturales finas y escasas quiere un look completo y voluminoso para su boda. Nunca ha tenido extensiones de pestañas."),
      q(10,"SCENARIO","What should you do?","¿Qué deberías hacer?",["Add more fans to compensate","Agregar más abanicos para compensar","Evaluate if the fan weight is too heavy and switch to a thinner diameter or fewer extensions per fan","Evaluar si el peso del abanico es demasiado pesado y cambiar a un diámetro más delgado o menos extensiones por abanico","Ignore it — some shedding is normal","Ignorarlo — algo de caída es normal","Tell the client to use more aftercare products","Decirle al cliente que use más productos de cuidado posterior"],"b","Rapid shedding of volume fans often indicates the fans are too heavy for the natural lashes.","La caída rápida de abanicos de volumen a menudo indica que los abanicos son demasiado pesados para las pestañas naturales.","You notice that your volume fans are shedding much faster than expected — clients are losing significant fans within the first week.","Notas que tus abanicos de volumen se están cayendo mucho más rápido de lo esperado — los clientes están perdiendo abanicos significativos dentro de la primera semana."),
    ],
  },

  // ────────────── MODULE 6 ──────────────
  {
    order: 6, isBonus: false,
    titleEn: "Lash Mapping & Styling",
    titleEs: "Mapeo y Estilización de Pestañas",
    subtitleEn: "Design looks that wow",
    subtitleEs: "Diseña looks que sorprendan",
    quizTitleEn: "Lash Mapping & Styling Quiz",
    quizTitleEs: "Examen de Mapeo y Estilización",
    lessons: [
      lesson(1,"Custom Mapping by Eye Shape","Mapeo Personalizado por Forma de Ojo","<p>Every client's eyes are unique, and your lash map should be customized accordingly. The key is to enhance natural beauty while addressing the client's desires.</p><p><strong>Almond eyes:</strong> The most versatile shape — most mapping styles work well. <strong>Round eyes:</strong> Cat eye mapping elongates. <strong>Hooded eyes:</strong> Use curlier extensions (D or L curl) to push lashes above the hood. <strong>Monolid:</strong> L or L+ curl with longer lengths creates lift. <strong>Downturned:</strong> Lift the outer corners with curlier extensions. <strong>Close-set:</strong> Keep inner corners short, longest at outer third. <strong>Wide-set:</strong> Place longest lengths at center to bring eyes together visually.</p>","<p>Los ojos de cada cliente son únicos, y tu mapa de pestañas debe personalizarse en consecuencia. La clave es realzar la belleza natural mientras se abordan los deseos del cliente.</p><p><strong>Ojos almendrados:</strong> La forma más versátil — la mayoría de los estilos de mapeo funcionan bien. <strong>Ojos redondos:</strong> El mapeo de ojo de gato alarga. <strong>Ojos encapotados:</strong> Usa extensiones más curvas (D o L) para empujar las pestañas sobre la capucha. <strong>Monopárpado:</strong> La curvatura L o L+ con longitudes más largas crea levantamiento. <strong>Ojos caídos:</strong> Levanta las esquinas externas con extensiones más curvas. <strong>Ojos juntos:</strong> Mantén las esquinas internas cortas, lo más largo en el tercio externo. <strong>Ojos separados:</strong> Coloca las longitudes más largas en el centro para acercar los ojos visualmente.</p>"),
      lesson(2,"Popular Styling Techniques","Técnicas de Estilización Populares","<p>Master these core styles to serve the majority of client requests:</p><p><strong>Cat Eye:</strong> Shortest at inner corner, progressively longer toward outer corner. Creates elongation. Best for round or close-set eyes.</p><p><strong>Doll Eye:</strong> Longest at center, shorter at both corners. Opens the eye vertically. Best for almond or narrow eyes.</p><p><strong>Natural:</strong> Follows the natural lash line with subtle enhancement. Slight peak at center with gradual taper. Best for clients wanting an \"I woke up like this\" look.</p><p><strong>Wispy:</strong> Alternating shorter and longer lengths to create a feathered, textured effect. Often combines different curls. Very popular on social media.</p>","<p>Domina estos estilos básicos para atender la mayoría de las solicitudes de los clientes:</p><p><strong>Ojo de Gato:</strong> Más corto en la esquina interna, progresivamente más largo hacia la esquina externa. Crea elongación. Mejor para ojos redondos o juntos.</p><p><strong>Ojo de Muñeca:</strong> Más largo en el centro, más corto en ambas esquinas. Abre el ojo verticalmente. Mejor para ojos almendrados o estrechos.</p><p><strong>Natural:</strong> Sigue la línea natural de pestañas con realce sutil. Pico ligero en el centro con disminución gradual. Mejor para clientes que buscan un look \"desperté así\".</p><p><strong>Wispy:</strong> Alternando longitudes más cortas y más largas para crear un efecto plumoso y texturizado. A menudo combina diferentes curvaturas. Muy popular en redes sociales.</p>"),
      lesson(3,"Correcting Asymmetrical Eyes","Corrección de Ojos Asimétricos","<p>Most people have some degree of facial asymmetry. As a lash artist, you can use mapping techniques to create the illusion of symmetry.</p><p><strong>Uneven eyelid creases:</strong> Use curlier extensions on the eye with a heavier lid to push lashes above the fold. <strong>Different eye sizes:</strong> Use slightly longer extensions on the smaller eye to create visual balance. <strong>Uneven lash lines:</strong> Adjust your map to compensate — more fullness where natural lashes are sparse.</p><p>Always assess both eyes open AND closed before mapping. What looks balanced when closed may appear uneven when the client is looking straight ahead with both eyes open.</p>","<p>La mayoría de las personas tienen algún grado de asimetría facial. Como artista de pestañas, puedes usar técnicas de mapeo para crear la ilusión de simetría.</p><p><strong>Pliegues desiguales del párpado:</strong> Usa extensiones más curvas en el ojo con un párpado más pesado para empujar las pestañas sobre el pliegue. <strong>Tamaños de ojos diferentes:</strong> Usa extensiones ligeramente más largas en el ojo más pequeño para crear equilibrio visual. <strong>Líneas de pestañas desiguales:</strong> Ajusta tu mapa para compensar — más plenitud donde las pestañas naturales son escasas.</p><p>Siempre evalúa ambos ojos abiertos Y cerrados antes de mapear. Lo que parece equilibrado cuando está cerrado puede parecer desigual cuando el cliente está mirando hacia adelante con ambos ojos abiertos.</p>"),
      lesson(4,"Layering for Texture & Dimension","Capas para Textura y Dimensión","<p><strong>Layering</strong> adds depth and dimension to a lash set by using multiple lengths within the same zone. Instead of uniform lengths, you alternate between shorter and longer extensions to create a more natural, textured appearance.</p><p>Techniques: <strong>Spike lashes</strong> (placing occasional longer extensions among shorter ones for a wispy effect), <strong>closed fans mixed with open fans</strong> for volume variation, and <strong>mixed curls</strong> within zones (e.g., C curl base with D curl spikes).</p><p>Layering is what separates advanced lash artists from beginners. It creates that coveted \"Instagram-worthy\" fluffy, dimensional look that clients love.</p>","<p><strong>Las capas</strong> agregan profundidad y dimensión a un set de pestañas usando múltiples longitudes dentro de la misma zona. En lugar de longitudes uniformes, alternas entre extensiones más cortas y más largas para crear una apariencia más natural y texturizada.</p><p>Técnicas: <strong>Pestañas pico</strong> (colocar extensiones más largas ocasionales entre las más cortas para un efecto wispy), <strong>abanicos cerrados mezclados con abanicos abiertos</strong> para variación de volumen, y <strong>curvaturas mixtas</strong> dentro de las zonas (por ejemplo, base de curvatura C con picos de curvatura D).</p><p>Las capas son lo que separa a los artistas de pestañas avanzados de los principiantes. Crea ese codiciado look esponjoso y dimensional digno de Instagram que las clientas aman.</p>"),
      lesson(5,"Advanced Styling Techniques","Técnicas de Estilización Avanzada","<p>As you grow in skill, explore these advanced techniques:</p><ul><li><strong>Kim K style:</strong> Dense, dark, and dramatic with consistent length and volume. Requires precise fan placement and perfect isolation.</li><li><strong>Wet look:</strong> Narrow, closed fans that create the appearance of individual clustered lashes — as if lashes are wet or freshly mascara'd.</li><li><strong>Ombre/colored lashes:</strong> Incorporating colored extensions (brown tips, colored tips, or full-color) for artistic effects.</li><li><strong>Bottom lash extensions:</strong> Applying small extensions (0.10mm, 5–7mm) to lower lashes for a complete, finished look.</li></ul><p>Always master the fundamentals before attempting advanced styles. Precision and consistency in basic techniques are the foundation of all advanced work.</p>","<p>A medida que crezcas en habilidad, explora estas técnicas avanzadas:</p><ul><li><strong>Estilo Kim K:</strong> Denso, oscuro y dramático con longitud y volumen consistentes. Requiere colocación precisa de abanicos y aislamiento perfecto.</li><li><strong>Look mojado:</strong> Abanicos estrechos y cerrados que crean la apariencia de pestañas individuales agrupadas — como si las pestañas estuvieran mojadas o recién con máscara.</li><li><strong>Pestañas ombre/coloreadas:</strong> Incorporar extensiones de color (puntas marrones, puntas de color o color completo) para efectos artísticos.</li><li><strong>Extensiones de pestañas inferiores:</strong> Aplicar extensiones pequeñas (0.10mm, 5–7mm) a las pestañas inferiores para un look completo y terminado.</li></ul><p>Siempre domina los fundamentos antes de intentar estilos avanzados. La precisión y consistencia en las técnicas básicas son la base de todo trabajo avanzado.</p>"),
    ],
    questions: [
      q(1,"MCQ","Which lash mapping style is best for round eyes?","¿Qué estilo de mapeo es mejor para ojos redondos?",["Doll Eye","Ojo de Muñeca","Cat Eye","Ojo de Gato","Open Eye","Ojo Abierto","Natural","Natural"],"b","Cat Eye mapping elongates round eyes by placing the longest extensions at the outer corner.","El mapeo de Ojo de Gato alarga los ojos redondos colocando las extensiones más largas en la esquina externa."),
      q(2,"MCQ","What curl type is recommended for hooded eyes?","¿Qué tipo de curvatura se recomienda para ojos encapotados?",["J curl","Curvatura J","D or L curl","Curvatura D o L","B curl","Curvatura B","No curl","Sin curvatura"],"b","Curlier extensions (D or L/L+) push the lashes above the hooded lid for visibility.","Las extensiones más curvas (D o L/L+) empujan las pestañas sobre el párpado encapotado para visibilidad."),
      q(3,"MCQ","What is the 'wispy' lash style?","¿Qué es el estilo de pestañas 'wispy'?",["All lashes the same length","Todas las pestañas de la misma longitud","Alternating shorter and longer lengths for a feathered, textured effect","Alternar longitudes más cortas y más largas para un efecto plumoso y texturizado","Only using J curl","Solo usar curvatura J","Applying extensions only to every other lash","Aplicar extensiones solo a cada otra pestaña"],"b","Wispy style alternates lengths and may mix curls to create a textured, feathery appearance.","El estilo wispy alterna longitudes y puede mezclar curvaturas para crear una apariencia texturizada y plumosa."),
      q(4,"MCQ","What are 'spike lashes' in layering?","¿Qué son las 'pestañas pico' en las capas?",["Damaged extensions","Extensiones dañadas","Occasionally placed longer extensions among shorter ones for dimension","Extensiones más largas colocadas ocasionalmente entre las más cortas para dimensión","Extensions applied to baby lashes","Extensiones aplicadas a pestañas bebé","A type of adhesive application","Un tipo de aplicación de adhesivo"],"b","Spike lashes are strategically placed longer extensions that create a wispy, dimensional texture.","Las pestañas pico son extensiones más largas colocadas estratégicamente que crean una textura wispy y dimensional."),
      q(5,"MCQ","How should you correct close-set eyes with lash mapping?","¿Cómo deberías corregir ojos juntos con mapeo de pestañas?",["Place longest lengths at inner corners","Colocar las longitudes más largas en esquinas internas","Keep inner corners short, place longest at outer third","Mantener esquinas internas cortas, colocar las más largas en el tercio externo","Use uniform length everywhere","Usar longitud uniforme en todo","Skip the inner corners entirely","Omitir las esquinas internas por completo"],"b","Short inner corners and longer outer sections draw the eyes apart visually.","Las esquinas internas cortas y secciones externas más largas alejan los ojos visualmente."),
      q(6,"MCQ","When should you assess eye symmetry during mapping?","¿Cuándo debes evaluar la simetría del ojo durante el mapeo?",["Only with eyes closed","Solo con ojos cerrados","Both eyes open AND closed","Ambos ojos abiertos Y cerrados","Only with eyes open","Solo con ojos abiertos","It doesn't matter","No importa"],"b","Assessment with both open and closed eyes ensures the map looks balanced in all positions.","La evaluación con ambos ojos abiertos y cerrados asegura que el mapa se vea equilibrado en todas las posiciones."),
      q(7,"MCQ","What is the 'wet look' lash style?","¿Qué es el estilo de pestañas 'look mojado'?",["Applying extensions with water","Aplicar extensiones con agua","Narrow, closed fans creating clustered individual-lash appearance","Abanicos estrechos y cerrados creando una apariencia de pestañas individuales agrupadas","Using gel adhesive","Usar adhesivo en gel","Extensions applied to wet lashes","Extensiones aplicadas a pestañas mojadas"],"b","The wet look uses narrow, closed fans to mimic the appearance of clumped, freshly mascara'd lashes.","El look mojado usa abanicos estrechos y cerrados para imitar la apariencia de pestañas agrupadas recién maquilladas."),
      q(8,"SCENARIO","What mapping approach would you recommend?","¿Qué enfoque de mapeo recomendarías?",["Standard cat eye map on both eyes","Mapa de ojo de gato estándar en ambos ojos","Use curlier extensions (D curl) on the hooded eye and standard C curl on the other to create visual balance","Usar extensiones más curvas (curvatura D) en el ojo encapotado y curvatura C estándar en el otro para crear equilibrio visual","The same map and curl on both eyes","El mismo mapa y curvatura en ambos ojos","Decline the service due to asymmetry","Rechazar el servicio debido a la asimetría"],"b","Using a curlier extension on the hooded eye pushes lashes above the fold, matching the visible lash line of the other eye.","Usar una extensión más curva en el ojo encapotado empuja las pestañas sobre el pliegue, igualando la línea de pestañas visible del otro ojo.","A client has one eye with a deeper lid crease (slightly hooded) while the other eye has a visible crease. She wants her lashes to look even on both sides.","Una clienta tiene un ojo con un pliegue del párpado más profundo (ligeramente encapotado) mientras el otro ojo tiene un pliegue visible. Quiere que sus pestañas se vean iguales en ambos lados."),
      q(9,"SCENARIO","What style would you recommend?","¿Qué estilo recomendarías?",["Full mega volume for dramatic effect","Mega volumen completo para efecto dramático","A doll eye map with C curl, moderate lengths (10–13mm), and natural layering","Un mapa de ojo de muñeca con curvatura C, longitudes moderadas (10–13mm) y capas naturales","Cat eye with D curl and maximum length","Ojo de gato con curvatura D y longitud máxima","Whatever is trending on Instagram","Lo que sea tendencia en Instagram"],"b","For a bridal look, a doll eye map with moderate lengths creates beautiful, natural-looking fullness that photographs well.","Para un look de novia, un mapa de ojo de muñeca con longitudes moderadas crea una plenitud hermosa y de aspecto natural que se fotografía bien.","A bride-to-be wants lashes for her wedding day. She has almond eyes and wants something full but elegant — not over-the-top. She's worried about extensions looking too heavy in photos.","Una futura novia quiere pestañas para el día de su boda. Tiene ojos almendrados y quiere algo lleno pero elegante — no exagerado. Le preocupa que las extensiones se vean demasiado pesadas en fotos."),
      q(10,"SCENARIO","What adjustments should you make?","¿Qué ajustes deberías hacer?",["Tell her the mapping was fine","Decirle que el mapeo estuvo bien","Lift the outer corner length, use a curlier extension at the outer third, and extend the cat-eye peak further inward","Levantar la longitud de la esquina externa, usar una extensión más curva en el tercio externo y extender el pico del ojo de gato más hacia adentro","Apply more extensions everywhere","Aplicar más extensiones en todo","Remove all extensions and start over","Remover todas las extensiones y empezar de nuevo"],"b","For downturned eyes, the outer corner needs extra curl and strategic length placement to create a lifting effect.","Para ojos caídos, la esquina externa necesita curvatura extra y colocación estratégica de longitud para crear un efecto de levantamiento.","A client with downturned eyes received a cat eye style from another artist but felt it made her eyes look droopy. She comes to you wanting a fix.","Una clienta con ojos caídos recibió un estilo de ojo de gato de otro artista pero sintió que hacía que sus ojos se vieran caídos. Viene a ti queriendo una corrección."),
    ],
  },
];
